### ISSUE TITLE
Bring the repository alive (fix the unfinished work)

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz-docker#1]
- [ ] Push the build container (for releases) to DockerHub (EBO)
 - [ ] Fix the Readme.md (EBO)
  - [ ] Improve the examples landing page by providing something similar to [ThreeJS examples](https://threejs.org/) or [iTowns examples](http://www.itowns-project.org/itowns/examples/) (VMA)
 - [ ] Illustrate how to run the examples (VMA): when a user testing the container and chooses a particular
    example e.g. GeoCoding widget) provide some information through the UI of what the user should do
    to play/test/lean-about that example. Note that there exist some documentation element in [Ud-Viz-template/Readme.md](https://github.com/VCityTeam/UD-Viz-Template) that can be promoted here (and thus removed from UD-Viz-template).

**Comment by valentinMachado** [comment]
resolve by PR https://github.com/VCityTeam/UD-Viz/pull/223
